### ISSUE TITLE
Top bar doesn't show up in fullscreen mode

### ISSUE THREAD

**Issue by franciszekjuras** [khuedoan98/one-line-firefox#2]
In fullscreen mode the bar on top of the screen autohides (as intended), but it doesn't show back when moving the cursor to the top edge of the screen.

**Comment by khuedoan** [comment]
You can delete line `38`:

```css
    margin-bottom: -1px !important;
```

It will show a thin line under the bar but it will behave as you want. I don't use fullscreen so I prefer not having that line.
